stages:
  extract_data:
    cmd: python src/data/data_collection.py
    deps:
    - data/raw/zipped/transactions.zip
    - src/data/data_collection.py
    outs:
    - data/raw/extracted/

  data_processing:
    cmd: python src/data/data_processing.py
    deps:
    - data/raw/extracted/transactions.txt
    - src/data/data_processing.py
    outs:
    - data/inprogress/interim_transactions.csv
    - data/inprogress/interim_transactions.h5
    metrics:
    - reports/data_processing_metrics.json:
        cache: false
    - reports/processing_summary.json:
        cache: false
    plots:
    - reports/data_exploration.txt:
        cache: false
    - reports/preprocess_n_analysis.txt:
        cache: false